[package]
name = "mini-rust"
version = "0.1.0"
authors = ["Jonathan Tran <jonnytran@gmail.com>"]
edition = "2021"

[dependencies]
argparse = "0.2.2"
lalrpop-util = { version = "0.19.12", features = ["lexer"] }
regex = "1.9.0"

[build-dependencies]
lalrpop = "0.19.12"
