[package]
name = "mini-rust"
version = "0.1.0"
authors = ["Jonathan Tran <jonnytran@gmail.com>"]
edition = "2018"

[dependencies]
argparse = "0.2.2"
lalrpop-util = "0.17.2"
regex = "1.5.5"

[build-dependencies]
lalrpop = "0.17.2"
